services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./api/src:/usr/src/app/src

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./client/src:/usr/src/app/src

volumes:
  pgadmin-data:
